// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/wal.proto

package walpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WalRecord is one serialized log entry on disk. data is opaque to the WAL.
type WalRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LogSequenceNumber uint64                 `protobuf:"varint,1,opt,name=log_sequence_number,json=logSequenceNumber,proto3" json:"log_sequence_number,omitempty"`
	Data              []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Checksum          uint32                 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WalRecord) Reset() {
	*x = WalRecord{}
	mi := &file_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalRecord) ProtoMessage() {}

func (x *WalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalRecord.ProtoReflect.Descriptor instead.
func (*WalRecord) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WalRecord) GetLogSequenceNumber() uint64 {
	if x != nil {
		return x.LogSequenceNumber
	}
	return 0
}

func (x *WalRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WalRecord) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

// WalSnapshot is a stored snapshot from the underlying stateful application.
// It covers all log entries up to and including upto_log_sequence_number.
type WalSnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UptoLogSequenceNumber uint64                 `protobuf:"varint,1,opt,name=upto_log_sequence_number,json=uptoLogSequenceNumber,proto3" json:"upto_log_sequence_number,omitempty"`
	Data                  []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Checksum              uint32                 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WalSnapshot) Reset() {
	*x = WalSnapshot{}
	mi := &file_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalSnapshot) ProtoMessage() {}

func (x *WalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalSnapshot.ProtoReflect.Descriptor instead.
func (*WalSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *WalSnapshot) GetUptoLogSequenceNumber() uint64 {
	if x != nil {
		return x.UptoLogSequenceNumber
	}
	return 0
}

func (x *WalSnapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WalSnapshot) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

var File_proto_wal_proto protoreflect.FileDescriptor

const file_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/wal.proto\x12\x03wal\"k\n" +
	"\tWalRecord\x12.\n" +
	"\x13log_sequence_number\x18\x01 \x01(\x04R\x11logSequenceNumber\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\rR\bchecksum\"v\n" +
	"\vWalSnapshot\x127\n" +
	"\x18upto_log_sequence_number\x18\x01 \x01(\x04R\x15uptoLogSequenceNumber\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\rR\bchecksumB*Z(github.com/pratyush-prateek/wal-go/walpbb\x06proto3"

var (
	file_proto_wal_proto_rawDescOnce sync.Once
	file_proto_wal_proto_rawDescData []byte
)

func file_proto_wal_proto_rawDescGZIP() []byte {
	file_proto_wal_proto_rawDescOnce.Do(func() {
		file_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)))
	})
	return file_proto_wal_proto_rawDescData
}

var file_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_wal_proto_goTypes = []any{
	(*WalRecord)(nil),   // 0: wal.WalRecord
	(*WalSnapshot)(nil), // 1: wal.WalSnapshot
}
var file_proto_wal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wal_proto_init() }
func file_proto_wal_proto_init() {
	if File_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wal_proto_goTypes,
		DependencyIndexes: file_proto_wal_proto_depIdxs,
		MessageInfos:      file_proto_wal_proto_msgTypes,
	}.Build()
	File_proto_wal_proto = out.File
	file_proto_wal_proto_goTypes = nil
	file_proto_wal_proto_depIdxs = nil
}
